# Generated by Django 3.0.6 on 2020-05-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_auto_20200506_0430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'Toppings'},
        ),
    ]
